<?php
require_once 'config/database.php';
require_once 'config/session.php';
requireLogin();

if (!isset($_SESSION['last_courier'])) {
    header('Location: add_courier.php');
    exit;
}

$courier = $_SESSION['last_courier'];

// Generate notes content
$content = "PARTY INFORMATION NOTES\n";
$content .= "======================\n\n";
$content .= "Courier ID: " . $courier['courier_id'] . "\n";
$content .= "Date: " . date('d M Y', strtotime($courier['created_date'])) . "\n\n";
$content .= "TO PARTY NAME: " . ($courier['to_party_name_note'] ?: $courier['to_party_name']) . "\n\n";
$content .= "FROM PARTY NAME: " . ($courier['from_party_name_note'] ?: $courier['from_party_name']) . "\n\n";
$content .= "Generated by: " . $_SESSION['agent_name'] . "\n";
$content .= "Generated on: " . date('d M Y, h:i A') . "\n";

// Set headers for download
header('Content-Type: text/plain');
header('Content-Disposition: attachment; filename="party_notes_' . $courier['courier_id'] . '.txt"');
header('Content-Length: ' . strlen($content));

echo $content;
exit;
?>